[package]
name = "rust_audio_shenanigans"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.2"
midly = "0.5.3"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "sync"] }
